### ISSUE TITLE
error while running running collect command

### ISSUE THREAD

**Issue by gurtejkochhar** [duo-labs/cloudmapper#91]
i received this error while running the collect command
Traceback (most recent call last):
  File "cloudmapper.py", line 68, in <module>
    main()
  File "cloudmapper.py", line 52, in main
    module = importer.find_module(command_name).load_module(full_package_name)
  File "<frozen importlib._bootstrap_external>", line 398, in _check_name_wrapper
ImportError: loader for collect cannot handle commands.collect

**Comment by 0xdabbad00** [comment]
Are you on Windows?  I did a quick google search and this was one of the top hits: https://stackoverflow.com/questions/45489289/python-importerror-loader-for-module-cannot-handle-mp-main

I just added the `collect` command yesterday and only tested it on my macOS system.

**Comment by gurtejkochhar** [comment]
Hi 0xdabbad00

No I am on Mac OS
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199

i think this is an issue with latest code commits, would be possible for you to check?

**Comment by 0xdabbad00** [comment]
This second issue is a bug, I'm fixing now.  I'm still not sure on the first issue though where you ran on macOS.

**Comment by 0xdabbad00** [comment]
The second issue should be resolved with the `ec2-describe-images.json`.

For the first issue on your macOS system, maybe ensure you are inside a `virtualenv` environment and ensure you have a `./commands/collect.py` file, which is this one: https://github.com/duo-labs/cloudmapper/blob/master/commands/collect.py

**Comment by gurtejkochhar** [comment]
actually i ran the virtualenv with python2.7 for the first issue and it worked so i guess issue is to run with python3

**Comment by nvisium-jonn-callahan** [comment]
I'm actually running into this same issue still. macOS 10.12.6 with Python 3.6.5 within a venv. The fix was as simple as replacing the `importer.find_module` line (54 atm) with `module = importlib.import_module(full_package_name)`. Had to go and clean up a bunch of `print "foo"` statements as well, though.

**Comment by Hindmalti** [comment]
Hello, I'm having the same error while collecting the data : 
I'm running it on a vm ubuntu16 with a python 2.7.12

> Traceback (most recent call last):
>   File "cloudmapper.py", line 72, in <module>
>     main()
>   File "cloudmapper.py", line 55, in main
>     module = importlib.import_module(full_package_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/home/hind/cloudmapper/commands/amis.py", line 7, in <module>
>     from shared.nodes import Account, Region
>   File "/home/hind/cloudmapper/shared/nodes.py", line 27, in <module>
>     from netaddr import IPNetwork, IPAddress
> ImportError: No module named netaddr
>

**Comment by Hindmalti** [comment]
Do you have an idea to solve this problem, please ? Thank's !

**Comment by Hindmalti** [comment]
I tried the command that you recommanded (even if i'm not on Mac OS)  : 

> ./commands/collect.py 

But, I got a permission denied while executing it, even if I'm sudo

**Comment by 0xdabbad00** [comment]
@Hindmalti It looks like you didn't follow the instructions to run inside a pipenv shell.  You need to run:
```
pipenv install --skip-lock
pipenv shell
```

Please see the rest of the instructions for setup.
